name: "Zalo Bot"
description: "Add-on Zalo Bot in Home Assistant"
url: "https://github.com/smarthomeblack/hass-addon"
version: "2026.5.15"
slug: "zalo_bot"
init: false
webui: "http://[HOST]:[PORT:3000]"
map:
  - config:rw
  - data:rw
  - share:rw
host_network: true
ports:
  3000/tcp: null
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
image: "ghcr.io/smarthomeblack/zalobot-{arch}"

options:
  data_directory: "/config/zalo_bot"
  port: 3000
schema:
  data_directory: "str"
  port: "int(1,65535)"